### ISSUE TITLE
Improvement opportunities

### ISSUE THREAD

**Issue by tgmendes** [KnowledgeCaptureAndDiscovery/wings-docker#2]
Hello,

I have some ideas that could further improve this repo:

- Optimize the Dockerfile (e.g. `apt update && apt install ...` should all be placed in one line);
- Creating a `docker-compose.yml` file which would effectively serve as a replacement for the `start_wings.sh` script (while still maintaining this script when compose is not available).

Would this be useful to you?

Regards,
Tiago

**Comment by dgarijo** [comment]
@tgmendes,
we welcome contributions, and  your suggestions look very useful. Please do a pull request and we will review it.
Thanks!

**Comment by tgmendes** [comment]
Hello,

I have opened a pull request with the changes  (#3).

Please review and check everything is working as expected (I haven't done thorough testing yet). 

There's still room for improvements, namely using environment variables for fine-tuning (e.g., WINGS_MODE is hardcoded and can be a variable passed through the docker-compose file). 

Hope this helps!

Regards,
Tiago

**Comment by dgarijo** [comment]
Thanks a lot! @varunratnakar  and I will review your PR and test it out!
Best regards,
Daniel

**Comment by tgmendes** [comment]
Glad to help! 

Note that I still haven't configured the compose and Dockerfile for genomics, so this image must be built "the old way".

Any issues with this new setup please tag me.

Regards,
Tiago
